motd:
  enabled: true
  pool:
    - "Warble Bink!"
    - "Mine your business"
    - "dig motherfucker"

mods:
  - name: jei
    url: https://mediafilez.forgecdn.net/files/6614/392/jei-1.21.1-neoforge-19.21.2.313.jar
  - name: sophisticatedbackpacks
    url: https://mediafilez.forgecdn.net/files/7343/948/sophisticatedbackpacks-1.21.11-3.25.18.1452.jar